package scb.dev.sms.sm.dao;

import scb.dev.sms.sm.pojo.Account;

public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_account
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	int deleteByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_account
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_account
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	int insertSelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_account
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	Account selectByPrimaryKey(String accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_account
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	int updateByPrimaryKeySelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_account
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	int updateByPrimaryKey(Account record);
}