package scb.dev.sms.sm.dao;

import java.util.List;

import scb.dev.sms.sm.pojo.Menu;
/**
 * 
 * @author Weilei
 *
 */
public interface MenuDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_menu
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_menu
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int insert(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_menu
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int insertSelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_menu
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	Menu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_menu
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_menu
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int updateByPrimaryKey(Menu record);
	
	List<Menu> selectAllMenu();
}