package scb.dev.sms.sm.dao;

import scb.dev.sms.sm.pojo.RoleGroupGrant;
import scb.dev.sms.sm.pojo.RoleGroupGrantKey;

public interface RoleGroupGrantMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_rolegroup_grant
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int deleteByPrimaryKey(RoleGroupGrantKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_rolegroup_grant
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int insert(RoleGroupGrant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_rolegroup_grant
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int insertSelective(RoleGroupGrant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_rolegroup_grant
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	RoleGroupGrant selectByPrimaryKey(RoleGroupGrantKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_rolegroup_grant
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int updateByPrimaryKeySelective(RoleGroupGrant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sm_rolegroup_grant
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	int updateByPrimaryKey(RoleGroupGrant record);
}