package scb.dev.sms.sm.pojo;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_id
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_name
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_password
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private String accountPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_updated_user
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private String accountUpdatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_updated_time
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private Date accountUpdatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_created_user
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private String accountCreatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_account.account_created_time
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    private Date accountCreatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_id
     *
     * @return the value of sm_account.account_id
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_id
     *
     * @param accountId the value for sm_account.account_id
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_name
     *
     * @return the value of sm_account.account_name
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_name
     *
     * @param accountName the value for sm_account.account_name
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_password
     *
     * @return the value of sm_account.account_password
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public String getAccountPassword() {
        return accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_password
     *
     * @param accountPassword the value for sm_account.account_password
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_updated_user
     *
     * @return the value of sm_account.account_updated_user
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public String getAccountUpdatedUser() {
        return accountUpdatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_updated_user
     *
     * @param accountUpdatedUser the value for sm_account.account_updated_user
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountUpdatedUser(String accountUpdatedUser) {
        this.accountUpdatedUser = accountUpdatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_updated_time
     *
     * @return the value of sm_account.account_updated_time
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public Date getAccountUpdatedTime() {
        return accountUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_updated_time
     *
     * @param accountUpdatedTime the value for sm_account.account_updated_time
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountUpdatedTime(Date accountUpdatedTime) {
        this.accountUpdatedTime = accountUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_created_user
     *
     * @return the value of sm_account.account_created_user
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public String getAccountCreatedUser() {
        return accountCreatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_created_user
     *
     * @param accountCreatedUser the value for sm_account.account_created_user
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountCreatedUser(String accountCreatedUser) {
        this.accountCreatedUser = accountCreatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_account.account_created_time
     *
     * @return the value of sm_account.account_created_time
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public Date getAccountCreatedTime() {
        return accountCreatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_account.account_created_time
     *
     * @param accountCreatedTime the value for sm_account.account_created_time
     *
     * @mbg.generated Tue Nov 13 11:46:19 CST 2018
     */
    public void setAccountCreatedTime(Date accountCreatedTime) {
        this.accountCreatedTime = accountCreatedTime;
    }
}