package scb.dev.sms.sm.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Menu {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_id
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_name
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_parentId
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuParentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_orderId
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuOrderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_url
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_updated_user
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuUpdatedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_updated_time
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private Date menuUpdatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_created_user
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private String menuCreatedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_menu.menu_created_time
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	private Date menuCreatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_id
	 * @return  the value of sm_menu.menu_id
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_id
	 * @param menuId  the value for sm_menu.menu_id
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_name
	 * @return  the value of sm_menu.menu_name
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_name
	 * @param menuName  the value for sm_menu.menu_name
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_parentId
	 * @return  the value of sm_menu.menu_parentId
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuParentid() {
		return menuParentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_parentId
	 * @param menuParentid  the value for sm_menu.menu_parentId
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuParentid(String menuParentid) {
		this.menuParentid = menuParentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_orderId
	 * @return  the value of sm_menu.menu_orderId
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuOrderid() {
		return menuOrderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_orderId
	 * @param menuOrderid  the value for sm_menu.menu_orderId
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuOrderid(String menuOrderid) {
		this.menuOrderid = menuOrderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_url
	 * @return  the value of sm_menu.menu_url
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuUrl() {
		return menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_url
	 * @param menuUrl  the value for sm_menu.menu_url
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_updated_user
	 * @return  the value of sm_menu.menu_updated_user
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuUpdatedUser() {
		return menuUpdatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_updated_user
	 * @param menuUpdatedUser  the value for sm_menu.menu_updated_user
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuUpdatedUser(String menuUpdatedUser) {
		this.menuUpdatedUser = menuUpdatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_updated_time
	 * @return  the value of sm_menu.menu_updated_time
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public Date getMenuUpdatedTime() {
		return menuUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_updated_time
	 * @param menuUpdatedTime  the value for sm_menu.menu_updated_time
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuUpdatedTime(Date menuUpdatedTime) {
		this.menuUpdatedTime = menuUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_created_user
	 * @return  the value of sm_menu.menu_created_user
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public String getMenuCreatedUser() {
		return menuCreatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_created_user
	 * @param menuCreatedUser  the value for sm_menu.menu_created_user
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuCreatedUser(String menuCreatedUser) {
		this.menuCreatedUser = menuCreatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_menu.menu_created_time
	 * @return  the value of sm_menu.menu_created_time
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public Date getMenuCreatedTime() {
		return menuCreatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_menu.menu_created_time
	 * @param menuCreatedTime  the value for sm_menu.menu_created_time
	 * @mbg.generated  Tue Nov 13 15:20:27 CST 2018
	 */
	public void setMenuCreatedTime(Date menuCreatedTime) {
		this.menuCreatedTime = menuCreatedTime;
	}

	private List<Menu> children;
    
    public List<Menu> getChildren() {
		return children;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}

	public Menu() {
		super();
		children = new ArrayList<Menu>();
	}

	public Menu(String menuId, String menuName, String menuParentid, String menuOrderid) {
		super();
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuParentid = menuParentid;
		this.menuOrderid = menuOrderid;
	}
}