package scb.dev.sms.sm.pojo;

public class RoleGroupGrantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_rolegroup_grant.rg_rolegroup_id
     *
     * @mbg.generated Tue Nov 13 15:20:27 CST 2018
     */
    private String rgRolegroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_rolegroup_grant.rg_menu_id
     *
     * @mbg.generated Tue Nov 13 15:20:27 CST 2018
     */
    private String rgMenuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_rolegroup_grant.rg_rolegroup_id
     *
     * @return the value of sm_rolegroup_grant.rg_rolegroup_id
     *
     * @mbg.generated Tue Nov 13 15:20:27 CST 2018
     */
    public String getRgRolegroupId() {
        return rgRolegroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_rolegroup_grant.rg_rolegroup_id
     *
     * @param rgRolegroupId the value for sm_rolegroup_grant.rg_rolegroup_id
     *
     * @mbg.generated Tue Nov 13 15:20:27 CST 2018
     */
    public void setRgRolegroupId(String rgRolegroupId) {
        this.rgRolegroupId = rgRolegroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_rolegroup_grant.rg_menu_id
     *
     * @return the value of sm_rolegroup_grant.rg_menu_id
     *
     * @mbg.generated Tue Nov 13 15:20:27 CST 2018
     */
    public String getRgMenuId() {
        return rgMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_rolegroup_grant.rg_menu_id
     *
     * @param rgMenuId the value for sm_rolegroup_grant.rg_menu_id
     *
     * @mbg.generated Tue Nov 13 15:20:27 CST 2018
     */
    public void setRgMenuId(String rgMenuId) {
        this.rgMenuId = rgMenuId;
    }
}