package scb.dev.sms.sm.pojo;

import java.util.Date;

public class RoleGroupGrant extends RoleGroupGrantKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_rolegroup_grant.rg_created_user
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	private String rgCreatedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_rolegroup_grant.rg_created_time
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	private Date rgCreatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_rolegroup_grant.rg_updated_user
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	private String rgUpdatedUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_rolegroup_grant.rg_updated_time
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	private Date rgUpdatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_rolegroup_grant.rg_created_user
	 * @return  the value of sm_rolegroup_grant.rg_created_user
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public String getRgCreatedUser() {
		return rgCreatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_rolegroup_grant.rg_created_user
	 * @param rgCreatedUser  the value for sm_rolegroup_grant.rg_created_user
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public void setRgCreatedUser(String rgCreatedUser) {
		this.rgCreatedUser = rgCreatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_rolegroup_grant.rg_created_time
	 * @return  the value of sm_rolegroup_grant.rg_created_time
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public Date getRgCreatedTime() {
		return rgCreatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_rolegroup_grant.rg_created_time
	 * @param rgCreatedTime  the value for sm_rolegroup_grant.rg_created_time
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public void setRgCreatedTime(Date rgCreatedTime) {
		this.rgCreatedTime = rgCreatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_rolegroup_grant.rg_updated_user
	 * @return  the value of sm_rolegroup_grant.rg_updated_user
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public String getRgUpdatedUser() {
		return rgUpdatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_rolegroup_grant.rg_updated_user
	 * @param rgUpdatedUser  the value for sm_rolegroup_grant.rg_updated_user
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public void setRgUpdatedUser(String rgUpdatedUser) {
		this.rgUpdatedUser = rgUpdatedUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_rolegroup_grant.rg_updated_time
	 * @return  the value of sm_rolegroup_grant.rg_updated_time
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public Date getRgUpdatedTime() {
		return rgUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_rolegroup_grant.rg_updated_time
	 * @param rgUpdatedTime  the value for sm_rolegroup_grant.rg_updated_time
	 * @mbg.generated  Tue Nov 13 16:30:40 CST 2018
	 */
	public void setRgUpdatedTime(Date rgUpdatedTime) {
		this.rgUpdatedTime = rgUpdatedTime;
	}
}